#!/bin/bash
#PBS -N step3_nathersvars
#PBS -P eg3
#PBS -q normalbw
#PBS -l walltime=00:30:00
#PBS -l mem=8GB
#PBS -l ncpus=2
#PBS -l jobfs=2GB
#PBS -l storage=gdata/eg3+gdata/xp65+gdata/mn51
#PBS -j oe
#PBS -o /home/565/dh4185/mn51-dh4185/repos_collab/nesp_bff/pbs_scripts/job_logs/step3_calc_missing_vars/
#PBS -m abe
#PBS -M david.hoffmann@bom.gov.au

set -euo pipefail

module use /g/data/xp65/public/modules
module load conda/analysis3-26.01
# export PYTHONNOUSERSITE=1

LOC="${LOC:?Need LOC}"

SCRIPT="/home/565/dh4185/mn51-dh4185/repos_collab/nesp_bff/step3_calc_missing_vars.py"

python "$SCRIPT" \
  --loc "$LOC" \
  --input_dir "/g/data/eg3/nesp_bff/step2_qdc_scaling/BARPA-R/" \
  --output_dir "/g/data/eg3/nesp_bff/step3_calc_missing_vars/"
