#!/bin/bash
#PBS -P eg3
#PBS -q normalbw
#PBS -N historical_step1
#PBS -l storage=gdata/xp65+gdata/eg3+gdata/kj66+gdata/mn51+gdata/ia39+gdata/py18+gdata/hq89
#PBS -l walltime=08:00:00,mem=32GB
#PBS -l ncpus=7
#PBS -m abe
#PBS -M david.hoffmann@bom.gov.au
#PBS -l jobfs=10GB

module use /g/data/xp65/public/modules
module load conda/analysis3

cd $PBS_O_WORKDIR

python3 -W ignore ../step1_extracting_variables.py --rcm=BARPA-R --scenario=historical --freq=1hr --startYear=1994 --endYear=2014 --nworkers=10
