#!/bin/bash
#PBS -P eg3
#PBS -q normalbw
#PBS -N rechunk_ccam
#PBS -l storage=gdata/eg3+gdata/mn51+gdata/hq89+scratch/eg3
#PBS -l walltime=03:00:00
#PBS -l mem=32GB
#PBS -l ncpus=1
#PBS -l jobfs=10GB
#PBS -m abe
#PBS -M david.hoffmann@bom.gov.au

module load nco

cd $PBS_O_WORKDIR

# Arguments: VAR GCM SCENARIO START_YEAR END_YEAR
VAR=$1
GCM=$2
SCENARIO=$3
START_YEAR=$4
END_YEAR=$5

bash ../rechunk_ccam.sh "$VAR" "$GCM" "$SCENARIO" "$START_YEAR" "$END_YEAR"

